// <auto-generated />
using DoMeAFavor.DataService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DoMeAFavor.DataService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180721051238_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoMeAFavor.DataService.Models.CompletedMission", b =>
                {
                    b.Property<int>("MissioinId");

                    b.Property<int>("UserId");

                    b.Property<DateTime>("CompleteTime");

                    b.Property<string>("Evaluation");

                    b.HasKey("MissioinId", "UserId");

                    b.ToTable("CompletedMissions");
                });

            modelBuilder.Entity("DoMeAFavor.DataService.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Message");

                    b.Property<string>("MissionName");

                    b.Property<int>("Points");

                    b.Property<int>("PublisherId");

                    b.HasKey("MissionId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("DoMeAFavor.DataService.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<int>("Class");

                    b.Property<string>("Major");

                    b.Property<string>("Password");

                    b.Property<int>("PhoneNumber");

                    b.Property<int>("Points");

                    b.Property<string>("RealName");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
