// <auto-generated />
using DoMeAFavor.DataService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DoMeAFavor.DataService.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoMeAFavor.DataService.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Message");

                    b.Property<string>("MissionName");

                    b.Property<int>("Points");

                    b.Property<int>("Type");

                    b.HasKey("MissionId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("DoMeAFavor.DataService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<string>("Class");

                    b.Property<string>("Major");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Points");

                    b.Property<string>("RealName");

                    b.Property<string>("UserId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DoMeAFavor.DataService.Models.UserMission", b =>
                {
                    b.Property<int>("MissioinId");

                    b.Property<int>("UserId");

                    b.Property<int?>("MissionId");

                    b.Property<int>("ReceiverId");

                    b.HasKey("MissioinId", "UserId");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMissions");
                });

            modelBuilder.Entity("DoMeAFavor.DataService.Models.UserMission", b =>
                {
                    b.HasOne("DoMeAFavor.DataService.Models.Mission", "Mission")
                        .WithMany("UserMissions")
                        .HasForeignKey("MissionId");

                    b.HasOne("DoMeAFavor.DataService.Models.User", "User")
                        .WithMany("UserMissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
